name: KiCAD Exports
on: [push]

jobs:
  make:
    runs-on: ubuntu-20.04
    steps:
    - uses: actions/checkout@v2
    - uses: nerdyscout/kicad-exports@v2.3
      with:
        config: kibot.yaml
        schema: 'comb-arcade-breakout-board/comb-arcade-breakout-board.sch'
        board: 'comb-arcade-breakout-board/comb-arcade-breakout-board.kicad_pcb'
        verbose: 1
    - run: find
    - uses: softprops/action-gh-release@v1
      if: startsWith(github.ref, 'refs/tags/')
      with:
        files: |
          example/ntsc.hex
          example/pal-60.hex
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
